version: '3'
services:
  cb:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - LOOKBACK=10
      - CURRENCY=BTC
      - SLEEP_SECONDS=10
    command:
      - python
      - /app/app.py
